// The 6502 backend: IR in, .prg out.
//
// It emits C rather than assembly, on purpose: LLVM-MOS does register
// allocation, zero-page allocation, and instruction selection better than a
// first-generation backend would, so the work here is a faithful translation
// of the IR and nothing more. The generated C is deliberately boring — every
// construct maps one-to-one, so reading it against the source is easy.
import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const C_TYPE = {
  u8: 'uint8_t', i8: 'int8_t',
  u16: 'uint16_t', i16: 'int16_t',
  u24: 'uint32_t', i24: 'int32_t',
  u32: 'uint32_t', i32: 'int32_t',
  bool: 'uint8_t',
};

const DRIVER = { vic20: 'mos-vic20-clang', c64: 'mos-c64-clang' };

// Per-target compile flags.
//
// The SDK's vic20 linker script defaults to a machine with 24K of RAM
// expansion (programs load at $1201). 8BitScript targets the UNEXPANDED
// VIC-20 first — 3583 bytes, load address $1001, the machine as sold — so the
// expansion symbol is pinned to 0. Fitting the small machine is the point;
// expanded configurations can become an option once someone actually needs
// one.
const TARGET_FLAGS = {
  vic20: ['-Wl,--defsym=__memory_expansion=0'],
  c64: [],
};

function emitExpression(expr) {
  switch (expr.kind) {
    case 'const': return String(expr.value);
    case 'ref': return expr.name;
    case 'binop':
      return `(${emitExpression(expr.left)} ${expr.operator} ${emitExpression(expr.right)})`;
    case 'unop':
      return `(${expr.operator}${emitExpression(expr.argument)})`;
    default:
      throw new Error(`backend-6502: unknown IR expression '${expr.kind}'`);
  }
}

function emitStatement(statement, indent) {
  const pad = '    '.repeat(indent);
  switch (statement.kind) {
    case 'assign':
      return `${pad}${statement.target} = ${emitExpression(statement.value)};\n`;
    case 'if': {
      let out = `${pad}if (${emitExpression(statement.test)}) {\n`;
      out += statement.then.map((s) => emitStatement(s, indent + 1)).join('');
      if (statement.else) {
        out += `${pad}} else {\n`;
        out += statement.else.map((s) => emitStatement(s, indent + 1)).join('');
      }
      return `${out}${pad}}\n`;
    }
    case 'while': {
      let out = `${pad}while (${emitExpression(statement.test)}) {\n`;
      out += statement.body.map((s) => emitStatement(s, indent + 1)).join('');
      return `${out}${pad}}\n`;
    }
    case 'block': {
      let out = `${pad}{\n`;
      out += statement.body.map((s) => emitStatement(s, indent + 1)).join('');
      return `${out}${pad}}\n`;
    }
    case 'return': return `${pad}return;\n`;
    case 'break': return `${pad}break;\n`;
    case 'continue': return `${pad}continue;\n`;
    case 'asm':
      // Inline 6502, held verbatim since the lexer. LLVM-MOS accepts GNU-style
      // asm statements; the body's own newlines are preserved.
      return `${pad}__asm__ volatile(\n${statement.text
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .map((line) => `${pad}    "${line.replace(/"/g, '\\"')}\\n"`)
        .join('\n')}\n${pad});\n`;
    default:
      throw new Error(`backend-6502: unknown IR statement '${statement.kind}'`);
  }
}

/** Generate the C translation unit for an IR program. */
export function emitC(ir) {
  let out = '/* Generated by 8bs. Do not edit: the source of truth is the .8bs file. */\n';
  out += '#include <stdint.h>\n\n';

  for (const g of ir.globals) {
    const type = C_TYPE[g.type];
    if (g.address !== null) {
      // A hardware register: a name for a fixed location, not storage.
      out += `#define ${g.name} (*(volatile ${type} *)0x${g.address.toString(16).toUpperCase()})\n`;
    } else {
      out += `${g.volatile ? 'volatile ' : ''}${type} ${g.name} = ${g.init};\n`;
    }
  }
  out += '\n';

  for (const fn of ir.functions) {
    const name = fn.name === 'main' ? 'main' : fn.name;
    const returnType = name === 'main' ? 'int' : 'void';
    out += `${returnType} ${name}(void) {\n`;
    out += fn.body.map((s) => emitStatement(s, 1)).join('');
    if (name === 'main') out += '    return 0;\n';
    out += '}\n\n';
  }
  return out;
}

/**
 * Compile IR to a .prg via LLVM-MOS.
 *
 * @param {object} ir
 * @param {{ target: 'vic20'|'c64', outFile: string }} options
 * @returns {Promise<{ ok: boolean, cFile?: string, error?: string }>}
 */
export async function buildPrg(ir, { target, outFile }) {
  const driverName = DRIVER[target];
  if (!driverName) return { ok: false, error: `backend-6502 has no driver for target '${target}'` };

  const home = process.env.LLVM_MOS_HOME;
  if (!home) {
    return {
      ok: false,
      error: "LLVM_MOS_HOME is not set. Run '8bs doctor' — docs/setup/llvm-mos.md covers the install.",
    };
  }
  const driver = join(home, 'bin', driverName);
  if (!existsSync(driver)) {
    return { ok: false, error: `${driver} does not exist. Run '8bs doctor'.` };
  }

  const cFile = outFile.replace(/\.prg$/, '.c');
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(cFile, emitC(ir), 'utf8');

  return new Promise((resolvePromise) => {
    const child = spawn(
      driver,
      ['-Os', ...TARGET_FLAGS[target], '-o', outFile, cFile],
      { stdio: ['ignore', 'pipe', 'pipe'] },
    );
    let stderr = '';
    child.stderr.on('data', (d) => { stderr += d; });
    child.on('close', (code) => {
      resolvePromise(code === 0
        ? { ok: true, cFile }
        : { ok: false, cFile, error: `${driverName} failed:\n${stderr}` });
    });
  });
}
