// The web backend: IR in, .wasm out.
//
// It emits AssemblyScript and hands it to asc. AssemblyScript's sized integer
// types match the machine types one-to-one, which is most of why it is the web
// target's language: `u8` means the same wrapped byte in both worlds. The one
// wrinkle is that AssemblyScript widens integer arithmetic to i32, so every
// store narrows back explicitly — `x = <u8>(x + 1)` — which is exactly the
// wrap-at-assignment semantics the design specifies for this target.
import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

const AS_TYPE = {
  u8: 'u8', i8: 'i8', u16: 'u16', i16: 'i16',
  u24: 'u32', i24: 'i32', u32: 'u32', i32: 'i32',
  bool: 'bool',
};

function emitExpression(expr) {
  switch (expr.kind) {
    case 'const': return String(expr.value);
    case 'ref': return expr.name;
    case 'binop':
      return `(${emitExpression(expr.left)} ${expr.operator} ${emitExpression(expr.right)})`;
    case 'unop':
      return `(${expr.operator}${emitExpression(expr.argument)})`;
    default:
      throw new Error(`backend-web: unknown IR expression '${expr.kind}'`);
  }
}

function emitStatement(statement, indent, types) {
  const pad = '    '.repeat(indent);
  switch (statement.kind) {
    case 'assign': {
      const type = types.get(statement.target) ?? 'i32';
      return `${pad}${statement.target} = <${type}>${emitExpression(statement.value)};\n`;
    }
    case 'if': {
      let out = `${pad}if (${emitExpression(statement.test)}) {\n`;
      out += statement.then.map((s) => emitStatement(s, indent + 1, types)).join('');
      if (statement.else) {
        out += `${pad}} else {\n`;
        out += statement.else.map((s) => emitStatement(s, indent + 1, types)).join('');
      }
      return `${out}${pad}}\n`;
    }
    case 'while': {
      let out = `${pad}while (${emitExpression(statement.test)}) {\n`;
      out += statement.body.map((s) => emitStatement(s, indent + 1, types)).join('');
      return `${out}${pad}}\n`;
    }
    case 'block': {
      let out = `${pad}{\n`;
      out += statement.body.map((s) => emitStatement(s, indent + 1, types)).join('');
      return `${out}${pad}}\n`;
    }
    case 'return': return `${pad}return;\n`;
    case 'break': return `${pad}break;\n`;
    case 'continue': return `${pad}continue;\n`;
    case 'asm':
      throw Object.assign(
        new Error('asm6502 blocks are 6502 code and cannot run on the web target'),
        { targetLimitation: true },
      );
    default:
      throw new Error(`backend-web: unknown IR statement '${statement.kind}'`);
  }
}

/**
 * Generate the AssemblyScript module for an IR program.
 *
 * @returns {{ ok: true, source: string } | { ok: false, error: string }}
 */
export function emitAssemblyScript(ir) {
  const types = new Map(ir.globals.map((g) => [g.name, AS_TYPE[g.type]]));
  let out = '// Generated by 8bs. Do not edit: the source of truth is the .8bs file.\n';

  for (const g of ir.globals) {
    if (g.address !== null) {
      return {
        ok: false,
        error: `'${g.name}' is mapped to hardware address 0x${g.address.toString(16)} with @address; ` +
          'there is no such hardware on the web target',
      };
    }
    // Exported so a host can observe the program's state; wasm mutable-global
    // exports are exactly this use case.
    out += `export let ${g.name}: ${AS_TYPE[g.type]} = ${g.init};\n`;
  }
  out += '\n';

  try {
    for (const fn of ir.functions) {
      out += `export function ${fn.name}(): void {\n`;
      out += fn.body.map((s) => emitStatement(s, 1, types)).join('');
      out += '}\n\n';
    }
  } catch (error) {
    if (error.targetLimitation) return { ok: false, error: error.message };
    throw error;
  }
  return { ok: true, source: out };
}

/** The asc binary, from this package's own dependencies. */
function findAsc() {
  const require = createRequire(import.meta.url);
  return require.resolve('assemblyscript/bin/asc.js');
}

/**
 * Compile IR to a .wasm via asc.
 *
 * @param {object} ir
 * @param {{ outFile: string }} options
 * @returns {Promise<{ ok: boolean, asFile?: string, error?: string }>}
 */
export async function buildWasm(ir, { outFile }) {
  const emitted = emitAssemblyScript(ir);
  if (!emitted.ok) return { ok: false, error: emitted.error };

  const asFile = outFile.replace(/\.wasm$/, '.ts');
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(asFile, emitted.source, 'utf8');

  return new Promise((resolvePromise) => {
    const child = spawn(
      process.execPath,
      [findAsc(), asFile, '-o', outFile, '-O3', '--runtime', 'stub'],
      { stdio: ['ignore', 'pipe', 'pipe'] },
    );
    let stderr = '';
    child.stderr.on('data', (d) => { stderr += d; });
    child.on('close', (code) => {
      resolvePromise(code === 0
        ? { ok: true, asFile }
        : { ok: false, asFile, error: `asc failed:\n${stderr}` });
    });
  });
}
