// The portable half of the web target: the JavaScript that actually runs a
// compiled program in a browser, in a form somebody can drop into a page
// that isn't ours.
//
// `8bs build --target web` writes three things out of this module —
// 8bitscript.js (the loader), worker.js (the machine), and coi.js (an
// opt-in cross-origin-isolation shim) — alongside program.wasm. index.html
// is then a twelve-line shell that calls the loader like anybody else would,
// so the page we ship and the page someone embeds take exactly the same
// path. There is no "our page" code path to drift away from the public one.
//
// ## Why a worker, and why isolation
//
// The program is the .wasm's one exported function. It owns a thread, loops
// forever if it wants to, and calls waitFrame() to wait for the next frame —
// so it runs in a Web Worker, and waitFrame() is a wasm import that blocks on
// Atomics.wait until the page releases a frame. The page is the video chip:
// it never calls into the program, it paints the program's screen memory
// every display refresh and writes a one-byte input snapshot into that same
// memory for @8bitscript/web/input to read.
//
// That memory has to be reachable from both sides at once, and this is the
// constraint everything about embedding follows from. Measured in Chromium
// 153 against a real compiled program, on a page with no COOP/COEP:
//
//   - `new WebAssembly.Memory({ shared: true })` succeeds, and a module
//     declaring shared memory instantiates fine. Shared memory itself is
//     *not* gated on isolation.
//   - Handing that memory to a worker is: `postMessage` throws
//     `DataCloneError: SharedArrayBuffer transfer requires
//     self.crossOriginIsolated` — for the SharedArrayBuffer and for the
//     WebAssembly.Memory object alike.
//
// So the gate is not on having shared memory, it is on *sharing* it. There is
// no arrangement of workers that dodges it either: a worker sitting inside a
// blocking waitFrame() never returns to its event loop, so it cannot receive
// an input message while a program is running — shared memory is not an
// optimization here, it is the only channel that works. Cross-origin
// isolation is therefore a real requirement, not a nicety, and the honest
// thing is to require it, detect it, and say so plainly when it's missing.
//
// Hosts that can send headers should (writeWebBundle emits `_headers`, and
// docs/web-embedding.md has Apache/nginx/Vercel forms). Hosts that can't —
// GitHub Pages, a shared CMS, someone's blog — load coi.js, which installs a
// service worker that adds the headers to its own origin's responses and
// reloads once. Verified end to end against a real build served by a plain
// static file server with no headers at all: crossOriginIsolated flips true
// and the program runs at frameRate. It is opt-in because it applies
// `COEP: require-corp` to the *embedder's whole page*, which can break their
// unrelated third-party images, scripts and frames. That is their call, not
// ours.
import { glyphTableLiteral } from './font8x8.mjs';
import {
  BORDER_PX, CHAR_BASE, CHAR_H, CHAR_W, COLOR_BASE, COLORS, GRID_COLS, GRID_ROWS,
  INNER_H, INNER_W, INPUT_OFFSET, InputEdge, KEY_TO_EDGE, SWIPE_THRESHOLD,
  ANY_BORDER_SCALE, BORDER_HAIRLINE_PX, FULL_BORDER_SCALE,
} from './web-layout.mjs';

// The two words the page and the worker share, in a SharedArrayBuffer beside
// the program's memory: how many logical frames the page has released, and
// how many the program has taken. Their difference is how far behind the
// program is.
export const ISSUED = 0;
export const CONSUMED = 1;

/**
 * worker.js: the machine the program runs on.
 *
 * It instantiates the program with the one import a program can have —
 * waitFrame(), blocking on the page's frame clock — hands the page its memory
 * to paint, and calls the program's one exported function.
 *
 * The wasm URL arrives in the start message rather than being resolved
 * against `self.location.href`, because the loader may have started this
 * worker from a `blob:` URL (so that a page can load 8bitscript.js from a
 * different origin, where `new Worker('worker.js')` would be blocked). Under
 * a blob URL there is no meaningful base to resolve a relative path against.
 */
export function renderWorker() {
  return `// Generated by 8bs build --target web. The machine a program runs on.
const ISSUED = ${ISSUED};
const CONSUMED = ${CONSUMED};

self.onmessage = async ({ data: { ctrl, wasmUrl } }) => {
  // Block until the page has released a frame this program hasn't taken yet.
  // Returns at once when one is already owed — two logical frames per real
  // one on a slow display — otherwise sleeps until the page notifies. The
  // same 0/1/2-frames-per-wait behavior the 6502 backend's accumulator has.
  const waitFrame = () => {
    const next = Atomics.load(ctrl, CONSUMED) + 1;
    for (let issued; (issued = Atomics.load(ctrl, ISSUED)) < next;) {
      Atomics.wait(ctrl, ISSUED, issued);
    }
    Atomics.store(ctrl, CONSUMED, next);
  };

  try {
    const response = await fetch(wasmUrl);
    if (!response.ok) throw new Error('could not load ' + wasmUrl + ' (HTTP ' + response.status + ')');
    const module = await WebAssembly.compile(await response.arrayBuffer());
    const shared = WebAssembly.Module.imports(module).some((i) => i.module === 'env' && i.name === 'waitFrame');
    const instance = await WebAssembly.instantiate(module, { env: { waitFrame } });
    const entry = Object.values(instance.exports).find((v) => typeof v === 'function');

    // A waitFrame() program's memory is shared, so the page can paint it while
    // the program runs. One that never waits has ordinary memory: it runs to
    // completion first, and the page gets a copy of the result to paint.
    if (shared) self.postMessage({ memory: instance.exports.memory.buffer });
    try {
      entry();
      if (!shared) self.postMessage({ memory: instance.exports.memory.buffer });
      self.postMessage({ done: true });
    } catch (error) {
      if (!shared) self.postMessage({ memory: instance.exports.memory.buffer });
      self.postMessage({ error: String(error) });
    }
  } catch (error) {
    self.postMessage({ error: String(error) });
  }
};
`;
}

/**
 * coi.js: the opt-in cross-origin-isolation shim.
 *
 * One file that is both the page script and the service worker it registers —
 * `window` tells the two apart. Included from a page, it registers itself,
 * and reloads once so the page comes back under a worker that stamps
 * COOP/COEP onto every response from this origin.
 *
 * This is how a host that cannot set headers (GitHub Pages and friends) runs
 * a program anyway. It is never loaded automatically: it changes the
 * *embedder's* whole page, not just the game.
 */
export function renderCoiServiceWorker() {
  return `// Generated by 8bs build --target web.
//
// Cross-origin isolation for hosts that cannot send headers. Include this
// BEFORE 8bitscript.js and it reloads the page once under a service worker
// that adds COOP/COEP to this origin's responses:
//
//   <script src="coi.js"></script>
//   <script src="8bitscript.js"></script>
//
// Read this before you do: it applies Cross-Origin-Embedder-Policy:
// require-corp to EVERY response on this origin, so any third-party image,
// script, frame or font your page loads must itself send
// Cross-Origin-Resource-Policy (or CORS) or it will stop loading. If you
// control your server, set the two headers there instead — see
// docs/web-embedding.md. If you only want this on one page, put the game in
// an <iframe> and load this shim inside the iframe only.
if (typeof window === 'undefined') {
  self.addEventListener('install', () => self.skipWaiting());
  self.addEventListener('activate', (event) => event.waitUntil(self.clients.claim()));
  self.addEventListener('fetch', (event) => {
    const request = event.request;
    // A range/cache revalidation the worker must not touch.
    if (request.cache === 'only-if-cached' && request.mode !== 'same-origin') return;
    event.respondWith(
      fetch(request)
        .then((response) => {
          // An opaque response has no headers to copy and no body to read.
          if (response.status === 0) return response;
          const headers = new Headers(response.headers);
          headers.set('Cross-Origin-Embedder-Policy', 'require-corp');
          headers.set('Cross-Origin-Opener-Policy', 'same-origin');
          headers.set('Cross-Origin-Resource-Policy', 'cross-origin');
          return new Response(response.body, {
            status: response.status,
            statusText: response.statusText,
            headers,
          });
        })
        .catch((error) => {
          console.error('8bitscript coi.js:', error);
          throw error;
        }),
    );
  });
} else {
  (function register(script) {
    if (window.crossOriginIsolated) return;
    // Service workers need HTTPS (or localhost). On plain http:// there is
    // nothing this can do, and the loader will say so.
    if (!window.isSecureContext || !navigator.serviceWorker) return;
    navigator.serviceWorker.register(script).then(
      (registration) => {
        registration.addEventListener('updatefound', () => window.location.reload());
        // Registered but not yet controlling this page: one reload and it is.
        if (registration.active && !navigator.serviceWorker.controller) window.location.reload();
      },
      (error) => console.error('8bitscript coi.js:', error),
    );
  })(document.currentScript && document.currentScript.src);
}
`;
}

// The default element name. Custom elements must contain a dash; this one
// says what it is rather than naming the project, because a page can host
// several and they are screens, not products.
export const ELEMENT_NAME = 'eightbit-screen';

/**
 * 8bitscript.js: the loader a page includes.
 *
 * A classic script, not a module, so `<script src>` works from any origin
 * without CORS or import-map ceremony. It defines `window.EightBitScript`
 * with `mount()` on it and registers the `<${ELEMENT_NAME}>` custom element.
 *
 * The worker source is embedded here as a string and started from a `blob:`
 * URL, so the whole loader is one file that works when it is served from a
 * different origin than the page — `new Worker('worker.js')` is blocked
 * cross-origin, a blob is not. Pages under a strict CSP that forbids
 * `worker-src blob:` can pass `worker: 'worker.js'` and get the same worker
 * from the same-origin file writeWebBundle also emits.
 *
 * @param {{ frameRate?: number }} [options]
 */
export function renderLoader({ frameRate = 60 } = {}) {
  return `// 8BitScript web loader. Generated by 8bs build --target web.
//
//   <script src="8bitscript.js"></script>
//   <eightbit-screen src="program.wasm"></eightbit-screen>
//
// or, with a handle to keep:
//
//   var screen = EightBitScript.mount('#game', { src: 'program.wasm' });
//   screen.destroy();
//
// Needs cross-origin isolation (COOP/COEP) — see docs/web-embedding.md, or
// load coi.js first on a host where you cannot set headers.
(function (global) {
  'use strict';

  var COLORS = ${JSON.stringify(COLORS)};
  var GLYPHS = ${glyphTableLiteral()};
  var GRID_COLS = ${GRID_COLS};
  var GRID_ROWS = ${GRID_ROWS};
  var CHAR_W = ${CHAR_W};
  var CHAR_H = ${CHAR_H};
  var INNER_W = ${INNER_W};
  var INNER_H = ${INNER_H};
  var BORDER_PX = ${BORDER_PX};
  var CHAR_BASE = ${CHAR_BASE};
  var COLOR_BASE = ${COLOR_BASE};
  var INPUT_OFFSET = ${INPUT_OFFSET};
  var KEY_TO_EDGE = ${JSON.stringify(KEY_TO_EDGE)};
  var SWIPE_THRESHOLD = ${SWIPE_THRESHOLD};
  var CONFIRM = ${InputEdge.CONFIRM};
  var DEFAULT_FRAME_RATE = ${frameRate};
  var ISSUED = ${ISSUED};
  var CONSUMED = ${CONSUMED};
  var ELEMENT_NAME = ${JSON.stringify(ELEMENT_NAME)};
  var WORKER_SOURCE = ${JSON.stringify(renderWorker())};
  var ISOLATION_HELP =
    'this page is not cross-origin isolated, so it cannot share memory with ' +
    'the program. Send Cross-Origin-Opener-Policy: same-origin and ' +
    'Cross-Origin-Embedder-Policy: require-corp, or load coi.js first.';

  // --- rules shared with the build (packages/cli/src/web-layout.mjs) -------
  // Both copies are checked against each other in web-loader.test.mjs, which
  // evaluates this file and compares it to the module it was generated from.

  function swipeEdge(dx, dy) {
    var ax = Math.abs(dx);
    var ay = Math.abs(dy);
    if (ax < SWIPE_THRESHOLD && ay < SWIPE_THRESHOLD) return 0;
    if (ax > ay) return dx < 0 ? ${InputEdge.LEFT} : ${InputEdge.RIGHT};
    return dy < 0 ? ${InputEdge.UP} : ${InputEdge.DOWN};
  }

  // The border is decoration, and on a small screen decoration is the first
  // thing that has to go: 48 of every 368 horizontal pixels and 48 of every
  // 248 vertical ones is a fifth of the height spent on nothing. A phone
  // renders the picture at barely 1-2x in either orientation, so it gets no
  // border at all and the game runs edge to edge. See web-layout.mjs.
  function borderFor(box) {
    var width = box && box.width;
    var height = box && box.height;
    if (!(width > 0) || !(height > 0)) return BORDER_PX;
    var scale = Math.min(width / INNER_W, height / INNER_H);
    if (scale < ${ANY_BORDER_SCALE}) return 0;
    if ((box && box.coarse) || scale < ${FULL_BORDER_SCALE}) return ${BORDER_HAIRLINE_PX};
    return BORDER_PX;
  }

  // --- the renderer -------------------------------------------------------

  function paintGlyph(ctx, x, y, rows, color) {
    ctx.fillStyle = color;
    for (var gy = 0; gy < 8; gy += 1) {
      var bits = rows[gy];
      for (var gx = 0; gx < 8; gx += 1) {
        if ((bits >> gx) & 1) ctx.fillRect(x + gx, y + gy, 1, 1);
      }
    }
  }

  // Whatever the program poked into the virtual character screen — this host
  // doesn't know or care what any of it means, the same way a real VIC-20/C64
  // doesn't know what a program's screen memory says. Byte 0 is border, byte 1
  // is background. Blank cells draw nothing unless reverse video (color bit 7)
  // is set: then the cell fills with the foreground and the glyph is punched
  // out in the background.
  function paint(ctx, mem, border) {
    var canvas = ctx.canvas;
    ctx.fillStyle = COLORS[mem[0] & 15];
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    var background = COLORS[mem[1] & 15];
    ctx.fillStyle = background;
    ctx.fillRect(border, border, INNER_W, INNER_H);
    // Clip to the inner rectangle — on the VIC-20/C64 characters cannot draw
    // in the border, and a glyph that overflowed a cell should not either.
    ctx.save();
    ctx.beginPath();
    ctx.rect(border, border, INNER_W, INNER_H);
    ctx.clip();
    for (var cell = 0; cell < GRID_COLS * GRID_ROWS; cell += 1) {
      var colorByte = mem[COLOR_BASE + cell];
      var reverse = (colorByte & 128) !== 0;
      var rows = GLYPHS[mem[CHAR_BASE + cell]] || null;
      if (rows === null && !reverse) continue;
      var col = cell % GRID_COLS;
      var row = (cell - col) / GRID_COLS;
      var x = border + col * CHAR_W;
      var y = border + row * CHAR_H;
      var fg = COLORS[colorByte & 15];
      if (reverse) {
        ctx.fillStyle = fg;
        ctx.fillRect(x, y, CHAR_W, CHAR_H);
        if (rows !== null) paintGlyph(ctx, x, y, rows, background);
      } else if (rows !== null) {
        paintGlyph(ctx, x, y, rows, fg);
      }
    }
    ctx.restore();
  }

  // --- helpers ------------------------------------------------------------

  function isolated() {
    return typeof SharedArrayBuffer !== 'undefined' && global.crossOriginIsolated !== false;
  }

  function coarsePointer() {
    return !!(global.matchMedia && global.matchMedia('(pointer: coarse)').matches);
  }

  function resolveHost(target) {
    if (!target) return null;
    if (typeof target === 'string') return document.querySelector(target);
    return target;
  }

  var workerUrlCache = null;
  function blobWorkerUrl() {
    if (workerUrlCache === null) {
      workerUrlCache = URL.createObjectURL(new Blob([WORKER_SOURCE], { type: 'text/javascript' }));
    }
    return workerUrlCache;
  }

  // --- mount --------------------------------------------------------------

  /**
   * Run a compiled program on a canvas inside \`target\`.
   * Returns a handle: { canvas, root, destroy(), isRunning() }.
   */
  function mount(target, options) {
    options = options || {};
    var host = resolveHost(target);
    if (!host) throw new Error('EightBitScript.mount: no such element: ' + target);
    var src = options.src;
    if (!src) throw new Error('EightBitScript.mount: options.src must be the URL of a .wasm program');
    // Resolved here, on the page, against the document's own base — the
    // worker may be a blob: URL with no base of its own to resolve against.
    var wasmUrl = new URL(src, document.baseURI).href;
    var frameRate = options.frameRate > 0 ? options.frameRate : DEFAULT_FRAME_RATE;
    var stepMs = 1000 / frameRate;
    var fullPage = !!options.fullPage;
    var fixedBorder = typeof options.border === 'number' ? options.border : null;
    var wantHud = !!options.hud;
    var hintText = options.hint || '';
    var allowFullscreen = options.fullscreen !== false;
    var keyboard = options.keyboard || (fullPage ? 'window' : 'focus');

    var root = document.createElement('div');
    root.className = 'eightbit-root';
    root.style.cssText =
      'position:relative;display:flex;align-items:center;justify-content:center;' +
      'background:#000;overflow:hidden;touch-action:none;' +
      (fullPage ? 'width:100%;height:100%;' : 'width:100%;height:100%;min-height:inherit;');
    if (keyboard === 'focus') {
      root.tabIndex = 0;
      root.style.outline = 'none';
    }

    var canvas = document.createElement('canvas');
    canvas.style.cssText = 'image-rendering:pixelated;display:block;touch-action:none;';
    root.appendChild(canvas);
    var ctx = canvas.getContext('2d');

    var hud = null;
    if (wantHud) {
      hud = document.createElement('div');
      hud.style.cssText =
        'position:absolute;top:8px;right:12px;pointer-events:none;' +
        'font:11px/1.4 ui-monospace,Menlo,monospace;color:rgba(255,255,255,0.4);';
      hud.textContent = 'FPS --';
      root.appendChild(hud);
    }

    var hint = document.createElement('div');
    hint.style.cssText =
      'position:absolute;left:50%;bottom:14px;transform:translateX(-50%);' +
      'max-width:90%;text-align:center;pointer-events:none;' +
      'font:12px/1.4 ui-monospace,Menlo,monospace;color:rgba(255,255,255,0.55);' +
      'background:rgba(0,0,0,0.35);padding:5px 10px;border-radius:6px;' +
      'transition:opacity .6s ease;opacity:' + (hintText ? '1' : '0');
    hint.textContent = hintText;
    root.appendChild(hint);
    var hintTimer = hintText ? setTimeout(function () { hint.style.opacity = '0'; }, 3000) : 0;
    function say(text) {
      clearTimeout(hintTimer);
      hint.textContent = text;
      hint.style.opacity = '1';
    }

    host.appendChild(root);

    // --- sizing -----------------------------------------------------------
    // Full-page reads visualViewport, the area actually visible right now:
    // mobile Safari's window.innerHeight can count space a collapsed toolbar
    // has given back, or not yet given back, depending on iOS version.
    // Embedded reads the host element — "small screen" there means a narrow
    // column in somebody's article, which visualViewport knows nothing about.
    var border = -1;
    function box() {
      if (fullPage) {
        var vv = global.visualViewport;
        return vv ? { width: vv.width, height: vv.height } : { width: global.innerWidth, height: global.innerHeight };
      }
      var rect = root.getBoundingClientRect();
      var width = rect.width || host.clientWidth || 0;
      var height = rect.height;
      // A bare <div> with no height of its own still has to be some shape.
      if (!(height > 0)) height = width * (INNER_H / INNER_W);
      return { width: width, height: height };
    }
    function resize() {
      var measured = box();
      var next = fixedBorder === null
        ? borderFor({ width: measured.width, height: measured.height, coarse: coarsePointer() })
        : fixedBorder;
      // Assigning canvas.width/height clears the canvas and resets every bit
      // of 2D context state, so only do it when the border actually changed.
      if (next !== border) {
        border = next;
        canvas.width = INNER_W + border * 2;
        canvas.height = INNER_H + border * 2;
        if (mem) paint(ctx, mem, border);
      }
      var scale = Math.min(measured.width / canvas.width, measured.height / canvas.height);
      if (!(scale > 0)) scale = 1;
      canvas.style.width = Math.max(1, Math.floor(canvas.width * scale)) + 'px';
      canvas.style.height = Math.max(1, Math.floor(canvas.height * scale)) + 'px';
      if (fullPage) {
        root.style.width = measured.width + 'px';
        root.style.height = measured.height + 'px';
      }
    }

    var observer = null;
    if (!fullPage && typeof ResizeObserver !== 'undefined') {
      observer = new ResizeObserver(resize);
      observer.observe(root);
    }
    global.addEventListener('resize', resize);
    document.addEventListener('fullscreenchange', resize);
    if (global.visualViewport) global.visualViewport.addEventListener('resize', resize);
    resize();

    // --- fullscreen -------------------------------------------------------
    function toggleFullscreen() {
      if (!allowFullscreen) return;
      if (document.fullscreenElement) {
        document.exitFullscreen();
      } else {
        var el = fullPage ? document.documentElement : root;
        if (el.requestFullscreen) el.requestFullscreen().catch(function () {});
      }
    }
    canvas.addEventListener('dblclick', toggleFullscreen);

    // --- input ------------------------------------------------------------
    var mem = null;
    var keysHeld = 0;
    function writeInput() {
      if (mem) mem[INPUT_OFFSET] = keysHeld;
    }
    function setInputBit(bit, down) {
      if (!bit) return;
      if (down) keysHeld |= bit;
      else keysHeld &= ~bit;
      writeInput();
    }
    // Embedded, the arrow keys belong to whoever has focus. Stealing them
    // from the whole document would break scrolling on the page we are a
    // guest in; full-page, there is nothing else to break.
    var keyTarget = keyboard === 'window' ? global : root;
    function onKeyDown(e) {
      var bit = KEY_TO_EDGE[e.key] || 0;
      if (bit) {
        e.preventDefault();
        setInputBit(bit, true);
      }
      if (allowFullscreen && (e.key === 'f' || e.key === 'F')) toggleFullscreen();
    }
    function onKeyUp(e) {
      var bit = KEY_TO_EDGE[e.key] || 0;
      if (bit) {
        e.preventDefault();
        setInputBit(bit, false);
      }
    }
    function releaseAll() {
      keysHeld = 0;
      writeInput();
    }
    keyTarget.addEventListener('keydown', onKeyDown);
    keyTarget.addEventListener('keyup', onKeyUp);
    keyTarget.addEventListener('blur', releaseAll);

    var pulseTimer = 0;
    function pulseBit(bit) {
      if (!bit) return;
      setInputBit(bit, true);
      clearTimeout(pulseTimer);
      pulseTimer = setTimeout(function () { setInputBit(bit, false); }, 80);
    }
    var pointerStart = null;
    function onPointerDown(e) {
      if (e.pointerType === 'mouse' && e.button !== 0) return;
      // A tap is also how an embedded screen takes the keyboard.
      if (keyboard === 'focus') root.focus({ preventScroll: true });
      pointerStart = { x: e.clientX, y: e.clientY };
      e.preventDefault();
    }
    function onPointerUp(e) {
      if (!pointerStart) return;
      var dx = e.clientX - pointerStart.x;
      var dy = e.clientY - pointerStart.y;
      pointerStart = null;
      e.preventDefault();
      pulseBit(swipeEdge(dx, dy) || CONFIRM);
    }
    canvas.addEventListener('pointerdown', onPointerDown);
    canvas.addEventListener('pointerup', onPointerUp);
    canvas.addEventListener('pointercancel', function () { pointerStart = null; });
    canvas.addEventListener('contextmenu', function (e) { e.preventDefault(); });

    // --- the frame clock --------------------------------------------------
    // Real elapsed time accumulates and is released to the program in fixed
    // logical steps. The program is *behind* by however many released frames
    // it hasn't taken yet; when that reaches two, a step is dropped rather
    // than banked — the same rule the 6502 backend's accumulator has. Without
    // it, a program that lagged would race through a backlog afterwards,
    // which no real machine does.
    var running = false;
    var destroyed = false;
    var worker = null;
    var ctrl = null;
    var acc = 0;
    var last = null;
    var fpsWindowStart = null;
    var fpsAtWindowStart = 0;
    var raf = 0;

    function tick(now) {
      if (destroyed) return;
      if (last === null) last = now;
      acc += now - last;
      last = now;
      // A backgrounded tab shouldn't spin through a huge backlog of logical
      // frames the instant it regains focus.
      if (acc > stepMs * 10) acc = stepMs * 10;
      while (acc >= stepMs) {
        acc -= stepMs;
        if (ctrl && Atomics.load(ctrl, ISSUED) - Atomics.load(ctrl, CONSUMED) < 2) {
          Atomics.add(ctrl, ISSUED, 1);
          Atomics.notify(ctrl, ISSUED);
        }
      }
      if (hud && ctrl) {
        if (fpsWindowStart === null) fpsWindowStart = now;
        if (now - fpsWindowStart >= 1000) {
          var consumed = Atomics.load(ctrl, CONSUMED);
          hud.textContent = 'FPS ' + (consumed - fpsAtWindowStart);
          if (options.onSample) options.onSample({ fps: consumed - fpsAtWindowStart, frames: consumed });
          fpsAtWindowStart = consumed;
          fpsWindowStart = now;
        }
      }
      if (mem) paint(ctx, mem, border);
      raf = requestAnimationFrame(tick);
    }

    function start() {
      if (running || destroyed) return;
      if (!isolated()) {
        say(ISOLATION_HELP);
        if (options.onError) options.onError(new Error(ISOLATION_HELP));
        return;
      }
      running = true;
      ctrl = new Int32Array(new SharedArrayBuffer(8));
      worker = new Worker(options.worker ? new URL(options.worker, document.baseURI).href : blobWorkerUrl());
      worker.onmessage = function (event) {
        var data = event.data;
        if (data.memory) {
          mem = new Uint8Array(data.memory);
          writeInput();
        }
        if (data.done) {
          say('the program finished');
          if (options.onDone) options.onDone();
        }
        if (data.error) {
          say('the program failed: ' + data.error);
          if (options.onError) options.onError(new Error(data.error));
        }
      };
      worker.onerror = function (e) { say('the program failed: ' + e.message); };
      worker.postMessage({ ctrl: ctrl, wasmUrl: wasmUrl });
      raf = requestAnimationFrame(tick);
    }

    function destroy() {
      if (destroyed) return;
      destroyed = true;
      running = false;
      cancelAnimationFrame(raf);
      clearTimeout(hintTimer);
      clearTimeout(pulseTimer);
      if (worker) worker.terminate();
      if (observer) observer.disconnect();
      global.removeEventListener('resize', resize);
      document.removeEventListener('fullscreenchange', resize);
      if (global.visualViewport) global.visualViewport.removeEventListener('resize', resize);
      keyTarget.removeEventListener('keydown', onKeyDown);
      keyTarget.removeEventListener('keyup', onKeyUp);
      keyTarget.removeEventListener('blur', releaseAll);
      if (root.parentNode) root.parentNode.removeChild(root);
      mem = null;
    }

    if (options.autoStart !== false) start();

    return {
      canvas: canvas,
      root: root,
      start: start,
      destroy: destroy,
      isRunning: function () { return running; },
      border: function () { return border; },
      say: say,
    };
  }

  // --- <eightbit-screen> --------------------------------------------------

  function defineElement() {
    if (typeof HTMLElement === 'undefined' || !global.customElements) return;
    if (global.customElements.get(ELEMENT_NAME)) return;
    function Screen() {
      return Reflect.construct(HTMLElement, [], Screen);
    }
    Screen.prototype = Object.create(HTMLElement.prototype);
    Screen.prototype.constructor = Screen;
    Object.setPrototypeOf(Screen, HTMLElement);
    Screen.prototype.connectedCallback = function () {
      if (this._screen) return;
      // An intrinsic shape, so dropping the tag into an article with no CSS
      // of its own still gives the picture somewhere to be. A stylesheet on
      // the host page overrides both, because this is only the default.
      if (!this.style.display) this.style.display = 'block';
      if (!this.style.aspectRatio) this.style.aspectRatio = INNER_W + ' / ' + INNER_H;
      var border = this.getAttribute('border');
      this._screen = mount(this, {
        src: this.getAttribute('src'),
        frameRate: Number(this.getAttribute('frame-rate')) || undefined,
        border: border === null || border === 'auto' ? undefined : Number(border),
        hud: this.hasAttribute('hud'),
        hint: this.getAttribute('hint') || '',
        fullscreen: this.getAttribute('fullscreen') !== 'off',
        worker: this.getAttribute('worker') || undefined,
      });
    };
    Screen.prototype.disconnectedCallback = function () {
      if (this._screen) this._screen.destroy();
      this._screen = null;
    };
    global.customElements.define(ELEMENT_NAME, Screen);
  }

  defineElement();

  global.EightBitScript = {
    mount: mount,
    borderFor: borderFor,
    swipeEdge: swipeEdge,
    defaultFrameRate: DEFAULT_FRAME_RATE,
    elementName: ELEMENT_NAME,
    COLORS: COLORS,
    layout: {
      innerWidth: INNER_W,
      innerHeight: INNER_H,
      cols: GRID_COLS,
      rows: GRID_ROWS,
      charBase: CHAR_BASE,
      colorBase: COLOR_BASE,
      inputOffset: INPUT_OFFSET,
      fullBorder: BORDER_PX,
    },
  };
})(typeof self !== 'undefined' ? self : this);
`;
}
