// The portable half of the web target: the JavaScript that actually runs a
// compiled program in a browser, in a form somebody can drop into a page
// that isn't ours.
//
// `8bs build --target web` writes three things out of this module —
// 8bitscript.js (the loader), worker.js (the machine), and coi.js (an
// opt-in cross-origin-isolation shim) — alongside program.wasm. index.html
// is then a twelve-line shell that calls the loader like anybody else would,
// so the page we ship and the page someone embeds take exactly the same
// path. There is no "our page" code path to drift away from the public one.
//
// ## Why a worker, and why isolation
//
// The program is the .wasm's one exported function. It owns a thread, loops
// forever if it wants to, and calls waitFrame() to wait for the next frame —
// so it runs in a Web Worker, and waitFrame() is a wasm import that blocks on
// Atomics.wait until the page releases a frame. The page is the video chip:
// it never calls into the program, it paints the program's screen memory
// every display refresh and writes a one-byte input snapshot into that same
// memory for @8bitscript/web/input to read.
//
// That memory has to be reachable from both sides at once, and this is the
// constraint everything about embedding follows from. Measured in Chromium
// 153 against a real compiled program, on a page with no COOP/COEP:
//
//   - `new WebAssembly.Memory({ shared: true })` succeeds, and a module
//     declaring shared memory instantiates fine. Shared memory itself is
//     *not* gated on isolation.
//   - Handing that memory to a worker is: `postMessage` throws
//     `DataCloneError: SharedArrayBuffer transfer requires
//     self.crossOriginIsolated` — for the SharedArrayBuffer and for the
//     WebAssembly.Memory object alike.
//
// So the gate is not on having shared memory, it is on *sharing* it. There is
// no arrangement of workers that dodges it either: a worker sitting inside a
// blocking waitFrame() never returns to its event loop, so it cannot receive
// an input message while a program is running — shared memory is not an
// optimization here, it is the only channel that works. Cross-origin
// isolation is therefore a real requirement, not a nicety, and the honest
// thing is to require it, detect it, and say so plainly when it's missing.
//
// Hosts that can send headers should (writeWebBundle emits `_headers`, and
// docs/web-embedding.md has Apache/nginx/Vercel forms). Hosts that can't —
// GitHub Pages, a shared CMS, someone's blog — load coi.js, which installs a
// service worker that adds the headers to its own origin's responses and
// reloads once. Verified end to end against a real build served by a plain
// static file server with no headers at all: crossOriginIsolated flips true
// and the program runs at frameRate. It is opt-in because it applies
// `COEP: require-corp` to the *embedder's whole page*, which can break their
// unrelated third-party images, scripts and frames. That is their call, not
// ours.
import { glyphTableLiteral } from './font8x8.mjs';
import {
  BORDER_PX, CHAR_BASE, CHAR_H, CHAR_W, COLOR_BASE, COLORS, DEFAULT_LAYOUT,
  GRID_COLS, GRID_ROWS, HOST_OFFSET, HostStatus,
  INNER_H, INNER_W, INPUT_OFFSET, InputEdge, KEY_TO_EDGE, SWIPE_THRESHOLD,
  ANY_BORDER_SCALE, BORDER_HAIRLINE_PX, BORDER_MIN_PX, FULL_BORDER_SCALE,
  COLUMNS_OFFSET, ROWS_OFFSET, MAX_COLUMNS, MAX_ROWS, MIN_COLUMNS, MIN_ROWS,
  RASTER_MAX_ENTRIES, TARGET_CELLS,
} from './web-layout.mjs';

// The two words the page and the worker share, in a SharedArrayBuffer beside
// the program's memory: how many logical frames the page has released, and
// how many the program has taken. Their difference is how far behind the
// program is.
export const ISSUED = 0;
export const CONSUMED = 1;

/**
 * worker.js: the machine the program runs on.
 *
 * It instantiates the program with the one import a program can have —
 * waitFrame(), blocking on the page's frame clock — hands the page its memory
 * to paint, and calls the program's one exported function.
 *
 * The wasm URL arrives in the start message rather than being resolved
 * against `self.location.href`, because the loader may have started this
 * worker from a `blob:` URL (so that a page can load 8bitscript.js from a
 * different origin, where `new Worker('worker.js')` would be blocked). Under
 * a blob URL there is no meaningful base to resolve a relative path against.
 */
export function renderWorker() {
  return `// Generated by 8bs build --target web. The machine a program runs on.
const ISSUED = ${ISSUED};
const CONSUMED = ${CONSUMED};

self.onmessage = async ({ data: { ctrl, wasmUrl, resizable, columnsOffset, rowsOffset, gridCols, gridRows } }) => {
  // Block until the page has released a frame this program hasn't taken yet.
  // Returns at once when one is already owed — two logical frames per real
  // one on a slow display — otherwise sleeps until the page notifies. The
  // same 0/1/2-frames-per-wait behavior the 6502 backend's accumulator has.
  const waitFrame = () => {
    const next = Atomics.load(ctrl, CONSUMED) + 1;
    for (let issued; (issued = Atomics.load(ctrl, ISSUED)) < next;) {
      Atomics.wait(ctrl, ISSUED, issued);
    }
    Atomics.store(ctrl, CONSUMED, next);
  };

  try {
    const response = await fetch(wasmUrl);
    if (!response.ok) throw new Error('could not load ' + wasmUrl + ' (HTTP ' + response.status + ')');
    const module = await WebAssembly.compile(await response.arrayBuffer());
    const shared = WebAssembly.Module.imports(module).some((i) => i.module === 'env' && i.name === 'waitFrame');
    const instance = await WebAssembly.instantiate(module, { env: { waitFrame } });
    const entry = Object.values(instance.exports).find((v) => typeof v === 'function');

    // The grid the page already measured, written here — before entry()
    // runs, on this thread, into this instance's own fresh memory — so
    // the program's first text.columns() read (inside its own start-up
    // layout, before it ever calls waitFrame) sees the real grid instead
    // of the compiled default. Writing it later, in response to the
    // memory this worker is about to post below, would be a second
    // thread reacting to a message this thread does not wait for — by
    // the time that write lands, entry() may already have used the
    // default. Only the Modern host sends resizable; every fixed skin
    // leaves it undefined and this is skipped, because columnsOffset
    // there is the screen's own first character cell, not a grid
    // register.
    if (resizable) {
      const mem = new Uint8Array(instance.exports.memory.buffer);
      mem[columnsOffset] = gridCols;
      mem[rowsOffset] = gridRows;
    }

    // A waitFrame() program's memory is shared, so the page can paint it while
    // the program runs. One that never waits has ordinary memory: it runs to
    // completion first, and the page gets a copy of the result to paint.
    if (shared) self.postMessage({ memory: instance.exports.memory.buffer });
    try {
      entry();
      if (!shared) self.postMessage({ memory: instance.exports.memory.buffer });
      self.postMessage({ done: true });
    } catch (error) {
      if (!shared) self.postMessage({ memory: instance.exports.memory.buffer });
      self.postMessage({ error: String(error) });
    }
  } catch (error) {
    self.postMessage({ error: String(error) });
  }
};
`;
}

/**
 * coi.js: the opt-in cross-origin-isolation shim.
 *
 * One file that is both the page script and the service worker it registers —
 * `window` tells the two apart. Included from a page, it registers itself,
 * and reloads once so the page comes back under a worker that stamps
 * COOP/COEP onto every response from this origin.
 *
 * This is how a host that cannot set headers (GitHub Pages and friends) runs
 * a program anyway. It is never loaded automatically: it changes the
 * *embedder's* whole page, not just the game.
 */
export function renderCoiServiceWorker() {
  return `// Generated by 8bs build --target web.
//
// Cross-origin isolation for hosts that cannot send headers. Include this
// BEFORE 8bitscript.js and it reloads the page once under a service worker
// that adds COOP/COEP to this origin's responses:
//
//   <script src="coi.js"></script>
//   <script src="8bitscript.js"></script>
//
// Read this before you do: it applies Cross-Origin-Embedder-Policy:
// require-corp to EVERY response on this origin, so any third-party image,
// script, frame or font your page loads must itself send
// Cross-Origin-Resource-Policy (or CORS) or it will stop loading. If you
// control your server, set the two headers there instead — see
// docs/web-embedding.md. If you only want this on one page, put the game in
// an <iframe> and load this shim inside the iframe only.
if (typeof window === 'undefined') {
  self.addEventListener('install', () => self.skipWaiting());
  self.addEventListener('activate', (event) => event.waitUntil(self.clients.claim()));
  self.addEventListener('fetch', (event) => {
    const request = event.request;
    // A range/cache revalidation the worker must not touch.
    if (request.cache === 'only-if-cached' && request.mode !== 'same-origin') return;
    event.respondWith(
      fetch(request)
        .then((response) => {
          // An opaque response has no headers to copy and no body to read.
          if (response.status === 0) return response;
          const headers = new Headers(response.headers);
          headers.set('Cross-Origin-Embedder-Policy', 'require-corp');
          headers.set('Cross-Origin-Opener-Policy', 'same-origin');
          headers.set('Cross-Origin-Resource-Policy', 'cross-origin');
          return new Response(response.body, {
            status: response.status,
            statusText: response.statusText,
            headers,
          });
        })
        .catch((error) => {
          console.error('8bitscript coi.js:', error);
          throw error;
        }),
    );
  });
} else {
  (function register(script) {
    if (window.crossOriginIsolated) return;
    // Service workers need HTTPS (or localhost). On plain http:// there is
    // nothing this can do, and the loader will say so.
    if (!window.isSecureContext || !navigator.serviceWorker) return;
    navigator.serviceWorker.register(script).then(
      (registration) => {
        registration.addEventListener('updatefound', () => window.location.reload());
        // Registered but not yet controlling this page: one reload and it is.
        if (registration.active && !navigator.serviceWorker.controller) window.location.reload();
      },
      (error) => console.error('8bitscript coi.js:', error),
    );
  })(document.currentScript && document.currentScript.src);
}
`;
}

// The default element name. Custom elements must contain a dash; this one
// says what it is rather than naming the project, because a page can host
// several and they are screens, not products.
export const ELEMENT_NAME = 'eightbit-screen';

/**
 * 8bitscript.js: the loader a page includes.
 *
 * A classic script, not a module, so `<script src>` works from any origin
 * without CORS or import-map ceremony. It defines `window.EightBitScript`
 * with `mount()` on it and registers the `<${ELEMENT_NAME}>` custom element.
 *
 * The worker source is embedded here as a string and started from a `blob:`
 * URL, so the whole loader is one file that works when it is served from a
 * different origin than the page — `new Worker('worker.js')` is blocked
 * cross-origin, a blob is not. Pages under a strict CSP that forbids
 * `worker-src blob:` can pass `worker: 'worker.js'` and get the same worker
 * from the same-origin file writeWebBundle also emits.
 *
 * @param {{ frameRate?: number, layout?: object }} [options]
 */
export function renderLoader({ frameRate = 60, layout = DEFAULT_LAYOUT } = {}) {
  return `// 8BitScript web loader. Generated by 8bs build --target web.
//
//   <script src="8bitscript.js"></script>
//   <eightbit-screen src="program.wasm"></eightbit-screen>
//
// or, with a handle to keep:
//
//   var screen = EightBitScript.mount('#game', { src: 'program.wasm' });
//   screen.destroy();
//
// Needs cross-origin isolation (COOP/COEP) — see docs/web-embedding.md, or
// load coi.js first on a host where you cannot set headers.
(function (global) {
  'use strict';

  var COLORS = ${JSON.stringify(layout.palette ?? COLORS)};
  var GLYPHS = ${glyphTableLiteral()};
  var GRID_COLS = ${layout.cols};
  var GRID_ROWS = ${layout.rows};
  var CHAR_W = ${layout.charWidth ?? CHAR_W};
  var CHAR_H = ${layout.charHeight ?? CHAR_H};
  var INNER_W = ${layout.innerWidth};
  var INNER_H = ${layout.innerHeight};
  var BORDER_PX = ${BORDER_PX};
  var CHAR_BASE = ${layout.charBase ?? CHAR_BASE};
  var COLOR_BASE = ${layout.colorBase};
  var INPUT_OFFSET = ${layout.inputOffset};
  var HOST_OFFSET = ${layout.hostOffset};
  var RASTER_CONTROL_OFFSET = ${layout.rasterControlOffset ?? DEFAULT_LAYOUT.rasterControlOffset};
  var RASTER_COUNT_OFFSET = ${layout.rasterCountOffset ?? DEFAULT_LAYOUT.rasterCountOffset};
  var RASTER_BASE = ${layout.rasterBase ?? DEFAULT_LAYOUT.rasterBase};
  var RASTER_MAX_ENTRIES = ${layout.rasterMaxEntries ?? RASTER_MAX_ENTRIES};
  var HOST_TOUCH = ${HostStatus.TOUCH};
  var HOST_NO_KEYBOARD = ${HostStatus.NO_KEYBOARD};
  var COLOR_PER_CELL = ${layout.colorPerCell !== false};
  var ASPECT = ${JSON.stringify(layout.aspect ?? '16/9')};
  // Modern only: the grid follows the window. Every machine skin is fixed,
  // because a skin is a machine. See packages/cli/src/web-layout.mjs.
  var RESIZABLE = ${layout.resizable === true};
  var COLUMNS_OFFSET = ${COLUMNS_OFFSET};
  var ROWS_OFFSET = ${ROWS_OFFSET};
  var MIN_COLUMNS = ${MIN_COLUMNS};
  var MAX_COLUMNS = ${MAX_COLUMNS};
  var MIN_ROWS = ${MIN_ROWS};
  var MAX_ROWS = ${MAX_ROWS};
  var TARGET_CELLS = ${TARGET_CELLS};
  var KEY_TO_EDGE = ${JSON.stringify(KEY_TO_EDGE)};
  var SWIPE_THRESHOLD = ${SWIPE_THRESHOLD};
  var CONFIRM = ${InputEdge.CONFIRM};
  var DEFAULT_FRAME_RATE = ${frameRate};
  var ISSUED = ${ISSUED};
  var CONSUMED = ${CONSUMED};
  var ELEMENT_NAME = ${JSON.stringify(ELEMENT_NAME)};
  var WORKER_SOURCE = ${JSON.stringify(renderWorker())};
  var ISOLATION_HELP =
    'this page is not cross-origin isolated, so it cannot share memory with ' +
    'the program. Send Cross-Origin-Opener-Policy: same-origin and ' +
    'Cross-Origin-Embedder-Policy: require-corp, or load coi.js first.';

  // --- rules shared with the build (packages/cli/src/web-layout.mjs, and,
  // for the raster compositor below, packages/cli/src/web-scanline.mjs) -----
  // Both copies are checked against each other in web-loader.test.mjs, which
  // evaluates this file and compares it to the modules it was generated from.

  function swipeEdge(dx, dy) {
    var ax = Math.abs(dx);
    var ay = Math.abs(dy);
    if (ax < SWIPE_THRESHOLD && ay < SWIPE_THRESHOLD) return 0;
    if (ax > ay) return dx < 0 ? ${InputEdge.LEFT} : ${InputEdge.RIGHT};
    return dy < 0 ? ${InputEdge.UP} : ${InputEdge.DOWN};
  }

  // Hold the cell count roughly constant and let the window pick the shape,
  // so text stays the same fraction of the screen at any size. 16:9 gives back
  // exactly the 48x27 this host has always had. Shared with the build; both
  // copies are checked against each other in web-loader.test.mjs.
  function gridFor(box) {
    var width = box && box.width;
    var height = box && box.height;
    if (!(width > 0) || !(height > 0)) return { cols: 48, rows: 27 };
    var cols = Math.round(Math.sqrt(TARGET_CELLS * (width / height)));
    cols = Math.min(MAX_COLUMNS, Math.max(MIN_COLUMNS, cols));
    var rows = Math.round(TARGET_CELLS / cols);
    rows = Math.min(MAX_ROWS, Math.max(MIN_ROWS, rows));
    return { cols: cols, rows: rows };
  }

  // The border is decoration, and on a small screen decoration is the first
  // thing that has to go: 48 of every 432 horizontal pixels (the default
  // 16:9 host) is a slice of the canvas spent on nothing. A phone renders the
  // picture at barely 1-2x in either orientation, so it gets the thinnest
  // border there is and the game runs very nearly edge to edge — but never
  // *no* border, because the border is a color a program sets to say
  // something about the whole screen. See web-layout.mjs.
  function borderFor(box) {
    var width = box && box.width;
    var height = box && box.height;
    if (!(width > 0) || !(height > 0)) return BORDER_PX;
    var scale = Math.min(width / INNER_W, height / INNER_H);
    if (scale < ${ANY_BORDER_SCALE}) return ${BORDER_MIN_PX};
    if ((box && box.coarse) || scale < ${FULL_BORDER_SCALE}) return ${BORDER_HAIRLINE_PX};
    return BORDER_PX;
  }

  // --- the renderer -------------------------------------------------------
  // The per-scanline compositor: a hand-mirrored copy of
  // packages/cli/src/web-scanline.mjs (readRasterEntries, rowState, and
  // renderFrame's row walk), the same arrangement swipeEdge/borderFor/gridFor
  // live under. Both copies are checked against each other, pixel for pixel,
  // in web-loader.test.mjs.

  function readRasterEntries(mem) {
    var enabled = mem[RASTER_CONTROL_OFFSET] !== 0;
    var count = mem[RASTER_COUNT_OFFSET];
    if (count > RASTER_MAX_ENTRIES) count = RASTER_MAX_ENTRIES;
    var entries = [];
    for (var i = 0; i < count; i += 1) {
      var at = RASTER_BASE + i * 3;
      // Bit 7 of the slot byte is the line's ninth bit: the resizable host
      // reaches 512 picture lines and a single line byte stops at 255.
      entries.push({
        line: mem[at] + ((mem[at + 1] & 128) === 0 ? 0 : 256),
        slot: mem[at + 1] & 127,
        value: mem[at + 2],
      });
    }
    return { enabled: enabled, entries: entries };
  }

  function rowState(entries, row, base) {
    var border = base.border;
    var background = base.background;
    var scrollX = 0;
    for (var i = 0; i < entries.length; i += 1) {
      var entry = entries[i];
      if (entry.line > row) break;
      if (entry.slot === 0) border = entry.value & 15;
      else if (entry.slot === 1) background = entry.value & 15;
      else if (entry.slot === 2) scrollX = entry.value & 7;
    }
    return { border: border, background: background, scrollX: scrollX };
  }

  // COLORS as [r, g, b] triples, re-parsed only when applyLayout swaps the
  // palette itself.
  var paletteCache = null;
  var paletteFrom = null;
  function paletteRgb() {
    if (paletteFrom !== COLORS) {
      paletteFrom = COLORS;
      paletteCache = [];
      for (var i = 0; i < COLORS.length; i += 1) {
        paletteCache.push([
          parseInt(COLORS[i].slice(1, 3), 16),
          parseInt(COLORS[i].slice(3, 5), 16),
          parseInt(COLORS[i].slice(5, 7), 16),
        ]);
      }
    }
    return paletteCache;
  }

  function fillSpan(rgba, offset, pixels, ink) {
    for (var i = 0; i < pixels; i += 1) {
      var at = offset + i * 4;
      rgba[at] = ink[0]; rgba[at + 1] = ink[1]; rgba[at + 2] = ink[2]; rgba[at + 3] = 255;
    }
  }

  // Whatever the program poked into the virtual character screen — this host
  // doesn't know or care what any of it means, the same way a real VIC-20/C64
  // doesn't know what a program's screen memory says. Byte 0 is border, byte 1
  // is background; the raster region past HOST_OFFSET can retint either, or
  // fine-scroll a band, from a line down. Blank cells draw nothing unless
  // reverse video (color bit 7) is set: then the cell fills with the
  // foreground and the glyph is punched out in the background. The compositor
  // never writes outside the inner rectangle — the border strips are its own
  // rows and columns — so the old clip-to-picture rule holds implicitly.
  var imageData = null;
  function paint(ctx, mem, border) {
    var canvas = ctx.canvas;
    var width = canvas.width;
    var height = canvas.height;
    // Re-dimensioned only when the canvas was — the same discipline
    // canvas.width/height themselves are under in resize().
    if (!imageData || imageData.width !== width || imageData.height !== height) {
      imageData = ctx.createImageData(width, height);
    }
    var rgba = imageData.data;
    var palette = paletteRgb();
    var base = {
      border: COLOR_PER_CELL ? mem[0] & 15 : 0,
      background: COLOR_PER_CELL ? mem[1] & 15 : 0,
    };
    var raster = readRasterEntries(mem);
    // Every slot applies on every skin. A skin without per-cell color keeps
    // its per-cell foreground fixed (palette[1], below), but BORDER and
    // BACKGROUND still resolve through the skin's palette — on the PET that
    // is black or green, which is exactly what a split means there.
    var entries = raster.enabled ? raster.entries : [];
    for (var y = 0; y < height; y += 1) {
      var row = y - border;
      var offset = y * width * 4;
      if (row < 0 || row >= INNER_H) {
        fillSpan(rgba, offset, width, palette[base.border]);
        continue;
      }
      var state = rowState(entries, row, base);
      var borderInk = palette[state.border];
      var backgroundInk = palette[state.background];
      fillSpan(rgba, offset, border, borderInk);
      fillSpan(rgba, offset + (border + INNER_W) * 4, width - border - INNER_W, borderInk);
      var glyphY = row % CHAR_H;
      var cellRow = (row - glyphY) / CHAR_H;
      for (var x = 0; x < INNER_W; x += 1) {
        var ink;
        var srcX = x - state.scrollX;
        if (srcX < 0) {
          ink = backgroundInk;
        } else {
          var gx = srcX % CHAR_W;
          var col = (srcX - gx) / CHAR_W;
          var cell = cellRow * GRID_COLS + col;
          var colorByte = mem[COLOR_BASE + cell];
          var reverse = (colorByte & 128) !== 0;
          var glyph = GLYPHS[mem[CHAR_BASE + cell]] || null;
          var bits = glyph === null ? 0 : glyph[glyphY];
          var on = ((bits >> gx) & 1) !== 0;
          var fg = COLOR_PER_CELL ? palette[colorByte & 15] : palette[1];
          ink = reverse ? (on ? backgroundInk : fg) : (on ? fg : backgroundInk);
        }
        var i = offset + (border + x) * 4;
        rgba[i] = ink[0]; rgba[i + 1] = ink[1]; rgba[i + 2] = ink[2]; rgba[i + 3] = 255;
      }
    }
    ctx.putImageData(imageData, 0, 0);
  }

  // --- helpers ------------------------------------------------------------

  function isolated() {
    return typeof SharedArrayBuffer !== 'undefined' && global.crossOriginIsolated !== false;
  }

  function coarsePointer() {
    return !!(global.matchMedia && global.matchMedia('(pointer: coarse)').matches);
  }

  function hostIsTouch() {
    var nav = global.navigator;
    var points = nav && nav.maxTouchPoints ? nav.maxTouchPoints : 0;
    var coarse = coarsePointer();
    if (points > 0 && coarse) return true;
    var ua = (nav && nav.userAgent) || '';
    if (points > 0 && /iPhone|iPad|iPod|Android/i.test(ua)) return true;
    return false;
  }

  function hoverNone() {
    return !!(global.matchMedia && global.matchMedia('(hover: none)').matches);
  }

  // No browser API says "a physical keyboard is attached". A touch host
  // whose primary pointer cannot hover is a phone or a tablet in the
  // hands, and starts out with no keyboard; a touchscreen laptop, or an
  // iPad on a trackpad keyboard, hovers and keeps its keyboard. sawKey
  // is the page's own evidence — a trusted keydown that did not come from
  // a text field — and outranks the guess: the iPad on a keyboard folio
  // with no trackpad gets its keyboard back at the first arrow it sends.
  // Mirrors hostHasKeyboard() in web-layout.mjs, which is the tested one.
  function hostHasKeyboard(sawKey) {
    if (sawKey) return true;
    return !(hostIsTouch() && hoverNone());
  }

  function applyLayout(next) {
    if (!next) return;
    // cols/rows/INNER_W/INNER_H, not on the Modern host: next here is the
    // program's own compiled sidecar (program.json), whose cols/rows are
    // the compiled DEFAULT (48x27) — informational on a resizable build,
    // not a live measurement. mount()'s own gridCols/gridRows (this
    // function cannot see them; they are a separate closure below) are
    // what a resizable host actually draws at, kept current by
    // resize()/applyGrid() instead. Applying the sidecar's cols/rows here
    // would overwrite INNER_W/INNER_H out from under that — and silently:
    // applyGrid()'s own change check only compares gridCols/gridRows, so
    // a resize() called right after this would see no change and skip
    // fixing INNER_W/INNER_H back, leaving the canvas painted at one grid
    // while the program (and this call's own postMessage to the worker)
    // uses another. On a fixed skin (RESIZABLE false) cols/rows genuinely
    // differ per machine, so this still has to run there.
    if (!RESIZABLE) {
      if (next.cols > 0) GRID_COLS = next.cols;
      if (next.rows > 0) GRID_ROWS = next.rows;
      if (next.charWidth > 0) CHAR_W = next.charWidth;
      if (next.charHeight > 0) CHAR_H = next.charHeight;
      INNER_W = GRID_COLS * CHAR_W;
      INNER_H = GRID_ROWS * CHAR_H;
    }
    if (next.charBase != null) CHAR_BASE = next.charBase;
    if (next.colorBase != null) COLOR_BASE = next.colorBase;
    if (next.inputOffset != null) INPUT_OFFSET = next.inputOffset;
    if (next.hostOffset != null) HOST_OFFSET = next.hostOffset;
    if (next.rasterControlOffset != null) RASTER_CONTROL_OFFSET = next.rasterControlOffset;
    if (next.rasterCountOffset != null) RASTER_COUNT_OFFSET = next.rasterCountOffset;
    if (next.rasterBase != null) RASTER_BASE = next.rasterBase;
    if (next.rasterMaxEntries != null) RASTER_MAX_ENTRIES = next.rasterMaxEntries;
    if (typeof next.colorPerCell === 'boolean') COLOR_PER_CELL = next.colorPerCell;
    if (next.aspect) ASPECT = next.aspect;
    if (next.palette && next.palette.length) COLORS = next.palette;
  }

  function resolveHost(target) {
    if (!target) return null;
    if (typeof target === 'string') return document.querySelector(target);
    return target;
  }

  var workerUrlCache = null;
  function blobWorkerUrl() {
    if (workerUrlCache === null) {
      workerUrlCache = URL.createObjectURL(new Blob([WORKER_SOURCE], { type: 'text/javascript' }));
    }
    return workerUrlCache;
  }

  // --- mount --------------------------------------------------------------

  /**
   * Run a compiled program on a canvas inside \`target\`.
   * Returns a handle: { canvas, root, destroy(), isRunning() }.
   */
  function mount(target, options) {
    options = options || {};
    var host = resolveHost(target);
    if (!host) throw new Error('EightBitScript.mount: no such element: ' + target);
    var src = options.src;
    if (!src) throw new Error('EightBitScript.mount: options.src must be the URL of a .wasm program');
    // Resolved here, on the page, against the document's own base — the
    // worker may be a blob: URL with no base of its own to resolve against.
    var wasmUrl = new URL(src, document.baseURI).href;
    var frameRate = options.frameRate > 0 ? options.frameRate : DEFAULT_FRAME_RATE;
    var stepMs = 1000 / frameRate;
    var fullPage = !!options.fullPage;
    var fixedBorder = typeof options.border === 'number' ? options.border : null;
    var wantHud = !!options.hud;
    var hintText = options.hint || '';
    var allowFullscreen = options.fullscreen !== false;
    var keyboard = options.keyboard || (fullPage ? 'window' : 'focus');

    var root = document.createElement('div');
    root.className = 'eightbit-root';
    root.style.cssText =
      'position:relative;display:flex;align-items:center;justify-content:center;' +
      'background:#000;overflow:hidden;touch-action:none;' +
      (fullPage ? 'width:100%;height:100%;' : 'width:100%;height:100%;min-height:inherit;');
    if (keyboard === 'focus') {
      root.tabIndex = 0;
      root.style.outline = 'none';
    }

    var canvas = document.createElement('canvas');
    canvas.style.cssText = 'image-rendering:pixelated;display:block;touch-action:none;';
    root.appendChild(canvas);
    var ctx = canvas.getContext('2d');

    var hud = null;
    if (wantHud) {
      hud = document.createElement('div');
      hud.style.cssText =
        'position:absolute;top:8px;right:12px;pointer-events:none;' +
        'font:11px/1.4 ui-monospace,Menlo,monospace;color:rgba(255,255,255,0.4);';
      hud.textContent = 'FPS --';
      root.appendChild(hud);
    }

    var hint = document.createElement('div');
    hint.style.cssText =
      'position:absolute;left:50%;bottom:14px;transform:translateX(-50%);' +
      'max-width:90%;text-align:center;pointer-events:none;' +
      'font:12px/1.4 ui-monospace,Menlo,monospace;color:rgba(255,255,255,0.55);' +
      'background:rgba(0,0,0,0.35);padding:5px 10px;border-radius:6px;' +
      'transition:opacity .6s ease;opacity:' + (hintText ? '1' : '0');
    hint.textContent = hintText;
    root.appendChild(hint);
    var hintTimer = hintText ? setTimeout(function () { hint.style.opacity = '0'; }, 3000) : 0;
    function say(text) {
      clearTimeout(hintTimer);
      hint.textContent = text;
      hint.style.opacity = '1';
    }

    host.appendChild(root);

    // --- sizing -----------------------------------------------------------
    // Full-page reads visualViewport, the area actually visible right now:
    // mobile Safari's window.innerHeight can count space a collapsed toolbar
    // has given back, or not yet given back, depending on iOS version.
    // Embedded reads the host element — "small screen" there means a narrow
    // column in somebody's article, which visualViewport knows nothing about.
    var border = -1;
    var gridCols = GRID_COLS;
    var gridRows = GRID_ROWS;

    // The grid the window asks for, written where the program reads it. Only
    // the Modern host does this; a machine skin's grid is its machine's, and
    // applyGrid() is a no-op there. Returns whether anything moved, because
    // the canvas has to be re-dimensioned when it did even if the border
    // happens to come out the same.
    function applyGrid(measured) {
      if (!RESIZABLE) return false;
      var grid = gridFor(measured);
      if (grid.cols === gridCols && grid.rows === gridRows) return false;
      gridCols = grid.cols;
      gridRows = grid.rows;
      GRID_COLS = gridCols;
      GRID_ROWS = gridRows;
      INNER_W = gridCols * CHAR_W;
      INNER_H = gridRows * CHAR_H;
      writeGrid();
      return true;
    }

    function writeGrid() {
      if (!RESIZABLE || !mem) return;
      mem[COLUMNS_OFFSET] = gridCols;
      mem[ROWS_OFFSET] = gridRows;
    }

    function box() {
      if (fullPage) {
        var vv = global.visualViewport;
        return vv ? { width: vv.width, height: vv.height } : { width: global.innerWidth, height: global.innerHeight };
      }
      var rect = root.getBoundingClientRect();
      var width = rect.width || host.clientWidth || 0;
      var height = rect.height;
      // A bare <div> with no height of its own still has to be some shape.
      if (!(height > 0)) height = width * (INNER_H / INNER_W);
      return { width: width, height: height };
    }
    // A resize while a waitFrame() program runs is applied between frames,
    // not the instant the window moves: the page holds the measurement and
    // re-grids in tick(), right before it releases the next frame, once the
    // program has consumed every frame issued so far — so it is waiting in
    // waitFrame(), and never sees columns() change between two reads inside
    // one frame. A program with no frame clock (it ran to completion, or has
    // not started) is re-gridded at once, as before.
    var pendingMeasure = null;
    function resize() {
      var measured = box();
      if (ctrl && !destroyed) {
        pendingMeasure = measured;
        fit(measured);
        return;
      }
      relayout(measured);
    }
    function relayout(measured) {
      var regridded = applyGrid(measured);
      var next = fixedBorder === null
        ? borderFor({ width: measured.width, height: measured.height, coarse: coarsePointer() })
        : fixedBorder;
      // Assigning canvas.width/height clears the canvas and resets every bit
      // of 2D context state, so only do it when the picture actually changed
      // shape — a new border, or a new grid under it.
      if (next !== border || regridded) {
        border = next;
        canvas.width = INNER_W + border * 2;
        canvas.height = INNER_H + border * 2;
        if (mem) paint(ctx, mem, border);
      }
      fit(measured);
    }
    // The canvas scaled into the measured box: safe at any moment, since it
    // changes no pixel the program can see.
    function fit(measured) {
      var scale = Math.min(measured.width / canvas.width, measured.height / canvas.height);
      if (!(scale > 0)) scale = 1;
      canvas.style.width = Math.max(1, Math.floor(canvas.width * scale)) + 'px';
      canvas.style.height = Math.max(1, Math.floor(canvas.height * scale)) + 'px';
      if (fullPage) {
        root.style.width = measured.width + 'px';
        root.style.height = measured.height + 'px';
      }
    }

    var observer = null;
    if (!fullPage && typeof ResizeObserver !== 'undefined') {
      observer = new ResizeObserver(resize);
      observer.observe(root);
    }
    global.addEventListener('resize', resize);
    document.addEventListener('fullscreenchange', resize);
    if (global.visualViewport) global.visualViewport.addEventListener('resize', resize);
    resize();

    // --- fullscreen -------------------------------------------------------
    function toggleFullscreen() {
      if (!allowFullscreen) return;
      if (document.fullscreenElement) {
        document.exitFullscreen();
      } else {
        var el = fullPage ? document.documentElement : root;
        if (el.requestFullscreen) el.requestFullscreen().catch(function () {});
      }
    }
    canvas.addEventListener('dblclick', toggleFullscreen);

    // --- input ------------------------------------------------------------
    var mem = null;
    var keysHeld = 0;
    function writeInput() {
      if (mem) mem[INPUT_OFFSET] = keysHeld;
    }
    // The host byte is levels, not presses: what this host is, for
    // @8bitscript/web/input's touch() and keyboard(). Written when the
    // memory arrives, and again the first time a real key proves the
    // keyboard guess wrong — the one bit in it that can change.
    var sawKey = false;
    function writeHost() {
      if (!mem) return;
      var status = hostIsTouch() ? HOST_TOUCH : 0;
      if (!hostHasKeyboard(sawKey)) status |= HOST_NO_KEYBOARD;
      mem[HOST_OFFSET] = status;
    }
    function isTextField(node) {
      if (!node || !node.tagName) return false;
      var tag = node.tagName.toUpperCase();
      return tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT' || node.isContentEditable === true;
    }
    // Any trusted key that is not typed into a form field is a keyboard.
    // A soft keyboard only ever appears for a text field, so a key from
    // outside one is a physical key — on a laptop, or plugged into a
    // tablet — and from then on the host has a keyboard.
    function noteKey(e) {
      if (sawKey || e.isTrusted === false || isTextField(e.target)) return;
      sawKey = true;
      writeHost();
    }
    function setInputBit(bit, down) {
      if (!bit) return;
      if (down) keysHeld |= bit;
      else keysHeld &= ~bit;
      writeInput();
    }
    // Embedded, the arrow keys belong to whoever has focus. Stealing them
    // from the whole document would break scrolling on the page we are a
    // guest in; full-page, there is nothing else to break.
    var keyTarget = keyboard === 'window' ? global : root;
    function onKeyDown(e) {
      noteKey(e);
      var bit = KEY_TO_EDGE[e.key] || 0;
      if (bit) {
        e.preventDefault();
        setInputBit(bit, true);
      }
      if (allowFullscreen && (e.key === 'f' || e.key === 'F')) toggleFullscreen();
    }
    function onKeyUp(e) {
      var bit = KEY_TO_EDGE[e.key] || 0;
      if (bit) {
        e.preventDefault();
        setInputBit(bit, false);
      }
    }
    function releaseAll() {
      keysHeld = 0;
      writeInput();
    }
    keyTarget.addEventListener('keydown', onKeyDown);
    keyTarget.addEventListener('keyup', onKeyUp);
    keyTarget.addEventListener('blur', releaseAll);

    var pulseTimer = 0;
    function pulseBit(bit) {
      if (!bit) return;
      setInputBit(bit, true);
      clearTimeout(pulseTimer);
      pulseTimer = setTimeout(function () { setInputBit(bit, false); }, 80);
    }
    var pointerStart = null;
    function onPointerDown(e) {
      if (e.pointerType === 'mouse' && e.button !== 0) return;
      // A tap is also how an embedded screen takes the keyboard.
      if (keyboard === 'focus') root.focus({ preventScroll: true });
      pointerStart = { x: e.clientX, y: e.clientY };
      e.preventDefault();
    }
    function onPointerUp(e) {
      if (!pointerStart) return;
      var dx = e.clientX - pointerStart.x;
      var dy = e.clientY - pointerStart.y;
      pointerStart = null;
      e.preventDefault();
      pulseBit(swipeEdge(dx, dy) || CONFIRM);
    }
    canvas.addEventListener('pointerdown', onPointerDown);
    canvas.addEventListener('pointerup', onPointerUp);
    canvas.addEventListener('pointercancel', function () { pointerStart = null; });
    canvas.addEventListener('contextmenu', function (e) { e.preventDefault(); });

    // --- the frame clock --------------------------------------------------
    // Real elapsed time accumulates and is released to the program in fixed
    // logical steps. The program is *behind* by however many released frames
    // it hasn't taken yet; when that reaches two, a step is dropped rather
    // than banked — the same rule the 6502 backend's accumulator has. Without
    // it, a program that lagged would race through a backlog afterwards,
    // which no real machine does.
    var running = false;
    var destroyed = false;
    var worker = null;
    var ctrl = null;
    var acc = 0;
    var last = null;
    var fpsWindowStart = null;
    var fpsAtWindowStart = 0;
    var raf = 0;

    function tick(now) {
      if (destroyed) return;
      if (last === null) last = now;
      acc += now - last;
      last = now;
      // A backgrounded tab shouldn't spin through a huge backlog of logical
      // frames the instant it regains focus.
      if (acc > stepMs * 10) acc = stepMs * 10;
      while (acc >= stepMs) {
        acc -= stepMs;
        if (ctrl && Atomics.load(ctrl, ISSUED) - Atomics.load(ctrl, CONSUMED) < 2) {
          // Between frames: the program has taken every frame released so
          // far and is waiting for this one. A pending resize lands here.
          if (pendingMeasure !== null && Atomics.load(ctrl, ISSUED) === Atomics.load(ctrl, CONSUMED)) {
            relayout(pendingMeasure);
            pendingMeasure = null;
          }
          Atomics.add(ctrl, ISSUED, 1);
          Atomics.notify(ctrl, ISSUED);
        }
      }
      if (hud && ctrl) {
        if (fpsWindowStart === null) fpsWindowStart = now;
        if (now - fpsWindowStart >= 1000) {
          var consumed = Atomics.load(ctrl, CONSUMED);
          hud.textContent = 'FPS ' + (consumed - fpsAtWindowStart);
          if (options.onSample) options.onSample({ fps: consumed - fpsAtWindowStart, frames: consumed });
          fpsAtWindowStart = consumed;
          fpsWindowStart = now;
        }
      }
      if (mem) paint(ctx, mem, border);
      raf = requestAnimationFrame(tick);
    }

    function start() {
      if (running || destroyed) return;
      if (!isolated()) {
        say(ISOLATION_HELP);
        if (options.onError) options.onError(new Error(ISOLATION_HELP));
        return;
      }
      running = true;
      ctrl = new Int32Array(new SharedArrayBuffer(8));
      worker = new Worker(options.worker ? new URL(options.worker, document.baseURI).href : blobWorkerUrl());
      worker.onmessage = function (event) {
        var data = event.data;
        if (data.memory) {
          mem = new Uint8Array(data.memory);
          writeInput();
          writeHost();
          // The program may already be running, so tell it the grid before it
          // asks. Until this lands, text.columns() answers with the compiled
          // default rather than with zero — see packages/web/src/geometry.8bs.
          writeGrid();
        }
        if (data.done) {
          say('the program finished');
          if (options.onDone) options.onDone();
        }
        if (data.error) {
          say('the program failed: ' + data.error);
          if (options.onError) options.onError(new Error(data.error));
        }
      };
      worker.onerror = function (e) { say('the program failed: ' + e.message); };
      // The grid the program should start with, written by the worker
      // itself before it calls the program's entry — not left to the
      // data.memory round trip above, which races the program's own first
      // frame: postMessage back to this thread is fire-and-forget, so the
      // worker calling entry() right after posting its memory can (and on
      // a fast machine reliably does) run text.columns()'s first read
      // before this thread has processed data.memory and called
      // writeGrid(). The visible failure is a program that lays itself
      // out for the compiled default (Video.columns() answers with it
      // until something writes the live bytes — see geometry.8bs) while
      // the page paints it at the grid gridFor() already measured: two
      // different widths applied to the same character buffer, which
      // reads as sheared, duplicated text. Only meaningful on the Modern
      // host — RESIZABLE is false everywhere else, and columnsOffset on a
      // fixed skin is the screen's own first character cell, not a grid
      // register, so the worker must not write there.
      worker.postMessage({
        ctrl: ctrl,
        wasmUrl: wasmUrl,
        resizable: RESIZABLE,
        columnsOffset: COLUMNS_OFFSET,
        rowsOffset: ROWS_OFFSET,
        gridCols: gridCols,
        gridRows: gridRows,
      });
      raf = requestAnimationFrame(tick);
    }

    function destroy() {
      if (destroyed) return;
      destroyed = true;
      running = false;
      cancelAnimationFrame(raf);
      clearTimeout(hintTimer);
      clearTimeout(pulseTimer);
      if (worker) worker.terminate();
      if (observer) observer.disconnect();
      global.removeEventListener('resize', resize);
      document.removeEventListener('fullscreenchange', resize);
      if (global.visualViewport) global.visualViewport.removeEventListener('resize', resize);
      keyTarget.removeEventListener('keydown', onKeyDown);
      keyTarget.removeEventListener('keyup', onKeyUp);
      keyTarget.removeEventListener('blur', releaseAll);
      if (root.parentNode) root.parentNode.removeChild(root);
      mem = null;
    }

    if (options.autoStart !== false) {
      var jsonUrl = wasmUrl.replace(/\.wasm(\\?.*)?$/, '.json$1');
      if (typeof fetch === 'function') {
        fetch(jsonUrl).then(function (response) {
          return response.ok ? response.json() : null;
        }).then(function (json) {
          applyLayout(json);
          border = -1;
          resize();
          start();
        }).catch(function () { start(); });
      } else {
        start();
      }
    }

    return {
      canvas: canvas,
      root: root,
      start: start,
      destroy: destroy,
      isRunning: function () { return running; },
      border: function () { return border; },
      say: say,
    };
  }

  // --- <eightbit-screen> --------------------------------------------------

  function defineElement() {
    if (typeof HTMLElement === 'undefined' || !global.customElements) return;
    if (global.customElements.get(ELEMENT_NAME)) return;
    function Screen() {
      return Reflect.construct(HTMLElement, [], Screen);
    }
    Screen.prototype = Object.create(HTMLElement.prototype);
    Screen.prototype.constructor = Screen;
    Object.setPrototypeOf(Screen, HTMLElement);
    Screen.prototype.connectedCallback = function () {
      if (this._screen) return;
      // An intrinsic shape, so dropping the tag into an article with no CSS
      // of its own still gives the picture somewhere to be. A stylesheet on
      // the host page overrides both, because this is only the default.
      if (!this.style.display) this.style.display = 'block';
      if (!this.style.aspectRatio) this.style.aspectRatio = ASPECT.replace('/', ' / ');
      var border = this.getAttribute('border');
      this._screen = mount(this, {
        src: this.getAttribute('src'),
        frameRate: Number(this.getAttribute('frame-rate')) || undefined,
        border: border === null || border === 'auto' ? undefined : Number(border),
        hud: this.hasAttribute('hud'),
        hint: this.getAttribute('hint') || '',
        fullscreen: this.getAttribute('fullscreen') !== 'off',
        worker: this.getAttribute('worker') || undefined,
      });
    };
    Screen.prototype.disconnectedCallback = function () {
      if (this._screen) this._screen.destroy();
      this._screen = null;
    };
    global.customElements.define(ELEMENT_NAME, Screen);
  }

  defineElement();

  global.EightBitScript = {
    mount: mount,
    borderFor: borderFor,
    gridFor: gridFor,
    swipeEdge: swipeEdge,
    // What the page will tell the program its host is, before any key has
    // been seen — so a shell can word its own hint the way the program
    // will word its prompt (index.html says "swipe to move" on a phone).
    hostIsTouch: hostIsTouch,
    hostHasKeyboard: function () { return hostHasKeyboard(false); },
    // Exposed the same way borderFor/gridFor/swipeEdge are: so the inlined
    // compositor can be held to web-scanline.mjs in web-loader.test.mjs.
    paint: paint,
    defaultFrameRate: DEFAULT_FRAME_RATE,
    elementName: ELEMENT_NAME,
    COLORS: COLORS,
    layout: {
      innerWidth: INNER_W,
      innerHeight: INNER_H,
      cols: GRID_COLS,
      rows: GRID_ROWS,
      charBase: CHAR_BASE,
      colorBase: COLOR_BASE,
      inputOffset: INPUT_OFFSET,
      hostOffset: HOST_OFFSET,
      aspect: ASPECT,
      resizable: RESIZABLE,
      fullBorder: BORDER_PX,
    },
  };
})(typeof self !== 'undefined' ? self : this);
`;
}
