// Regenerates packages/c64/src/chargen.8bs, the C64's character ROM as data,
// from the ROM image VICE ships:
//
//   node packages/c64/scripts/chargen-web.mjs [path/to/chargen-901225-01.bin]
//
// The image is 4096 bytes: two sets of 256 glyphs, eight bytes a glyph, the
// byte's bit 7 the leftmost pixel — the order the VIC-II reads it in. Set 0
// (the first 2048 bytes) is upper case and graphics, set 1 (the second)
// lower and upper case; each set holds 128 glyphs and then their 128 reversed
// copies, which is why reverse video is nothing but a screen code's bit 7.
//
// Only the C64's web build links the result (index.c64.web.8bs copies it to
// $D000, where the native build's setupVideo() copies the ROM itself): the
// page then draws every glyph out of the program's own memory, so a glyph the
// program redefines, or charset.restore()s, is simply the bytes there.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const romPath = process.argv[2] ?? '/opt/homebrew/share/vice/C64/chargen-901225-01.bin';
const rom = readFileSync(romPath);
if (rom.length !== 4096) throw new Error(`${romPath}: ${rom.length} bytes, expected the 4096-byte character ROM`);
const sha = createHash('sha256').update(rom).digest('hex').slice(0, 16);

const rows = [];
for (let i = 0; i < rom.length; i += 16) {
  rows.push('    ' + [...rom.subarray(i, i + 16)].map((b) => '0x' + b.toString(16).toUpperCase().padStart(2, '0')).join(', ') + ',');
}

const text = `// GENERATED by packages/c64/scripts/chargen-web.mjs — do not edit.
//
// The C64's character ROM (VICE's chargen-901225-01.bin, sha256 ${sha}…), as
// data: 4096 bytes, two sets of 256 glyphs of eight bytes, bit 7 the leftmost
// pixel. Set 0 is upper case and graphics, set 1 lower and upper case; codes
// 128-255 of each are the reversed copies. Linked only by index.c64.web.8bs,
// which copies it to $D000 the way the native setupVideo() copies the ROM, so
// the page draws from the program's own memory (see that file).
export const CHARGEN: array<u8, 4096> = [
${rows.join('\n')}
];
`;
writeFileSync(join(here, '..', 'src', 'chargen.8bs'), text);
process.stdout.write(`wrote packages/c64/src/chargen.8bs (${rom.length} bytes, sha256 ${sha}…)\n`);
