// Regenerates packages/cli/src/font-roms.mjs, the graphics half of the PET's
// and the VIC-20's character ROMs, from the images VICE ships:
//
//   node packages/cli/scripts/font-roms.mjs
//
// The wasm page draws these machines' text from a host font table
// (font8x8.mjs). The text halves are already there, captured earlier; this adds
// the set each machine BOOTS in, so a program that selects the other one with
// the machine's own register (the PET's POKE 59468, the VIC-20's $9005) is
// drawn the way the real chip draws it:
//
//   PET      two sets of 128 glyphs, 1024 bytes each: set 0 is graphics and
//            upper case (what the machine boots in), set 1 lower and upper
//            case. A screen code's bit 7 is not in the ROM at all: the video
//            circuit inverts the glyph.
//   VIC-20   the 6560 reads code 0-255 from the chargen base the low nybble of
//            $9005 names; the ROM holds each 128-glyph set followed by its
//            reversed copies. Set 0 ($8000) is upper case and graphics.
//
// The script takes no path: it looks for the images in the places VICE
// installs them, and writes the data only if each is the exact ROM pinned
// below (a SHA-256), so it can produce these tables and nothing else. It also
// checks the claim the page relies on: that the ROM's reversed copies are the
// plain inversion of the glyph they follow, so the page may invert.
//
// Every byte is bit-reversed here, because the page reads bit 0 as the
// leftmost pixel and the ROMs are read MSB-first.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const DIRS = ['/opt/homebrew/share/vice', '/usr/local/share/vice', '/usr/share/vice'];

const ROMS = {
  PET_2001: {
    file: 'PET/characters-1.901447-08.bin',
    length: 2048,
    sha256: '697390d9cd7da9e77d71935b0bf71d1181f624e0be802cbfb472803861443340',
  },
  PET: {
    file: 'PET/characters-2.901447-10.bin',
    length: 2048,
    sha256: 'da3374c21d6ea440cef5f338ce3f524e0a1e40dcb1ef64446c695f92c636f1fa',
  },
  VIC20: {
    file: 'VIC20/chargen-901460-03.bin',
    length: 4096,
    sha256: 'bda280726cfe069ca70ef5e2f2d95a29f69d3950c859a12e6979464963fcf502',
  },
};

const bitrev = (x) => {
  let r = 0;
  for (let i = 0; i < 8; i += 1) if (x & (1 << i)) r |= 1 << (7 - i);
  return r;
};

function load(name) {
  const spec = ROMS[name];
  const found = DIRS.map((d) => join(d, spec.file)).find((p) => existsSync(p));
  if (!found) throw new Error(`VICE's ${spec.file} is not under any of:\n  ${DIRS.join('\n  ')}`);
  const rom = readFileSync(found);
  const sha = createHash('sha256').update(rom).digest('hex');
  if (rom.length !== spec.length || sha !== spec.sha256) {
    throw new Error(`${found} is not the ROM ${name} is pinned to (${rom.length} bytes, sha256 ${sha})`);
  }
  return { rom, sha };
}

const slice = (rom, from, to) => Buffer.from([...rom.subarray(from, to)].map(bitrev));

const pet1 = load('PET_2001');
const pet2 = load('PET');
const vic = load('VIC20');

// The VIC-20's reversed copies are the plain inversion of the set before them.
for (const [label, plain, reversed] of [['set 0', 0x000, 0x400], ['set 1', 0x800, 0xc00]]) {
  for (let i = 0; i < 1024; i += 1) {
    if ((vic.rom[plain + i] ^ 0xff) !== vic.rom[reversed + i]) {
      throw new Error(`VIC-20 chargen ${label}: byte ${i} of the reversed copy is not the inversion of the glyph`);
    }
  }
}

const b64 = (buf) => buf.toString('base64').replace(/(.{100})/g, "$1' +\n  '");
const text = `// GENERATED by packages/cli/scripts/font-roms.mjs — do not edit.
//
// The graphics set each of these machines boots in, from the ROM images VICE
// ships, 128 glyphs of eight bytes each, bit 0 the leftmost pixel (the ROMs'
// own order reversed). The text sets are the tables in font8x8.mjs. A screen
// code's bit 7 is the glyph inverted — the PET's video circuit does it, and the
// VIC-20 ROM's reversed copies are exactly that inversion (the generator checks).
//
//   PET_2001_GRAPHICS  characters-1.901447-08.bin  sha256 ${pet1.sha.slice(0, 16)}…  first 1024 bytes
//   PET_GRAPHICS       characters-2.901447-10.bin  sha256 ${pet2.sha.slice(0, 16)}…  first 1024 bytes
//   VIC20_UPPER        chargen-901460-03.bin       sha256 ${vic.sha.slice(0, 16)}…  first 1024 bytes
export const PET_2001_GRAPHICS_B64 =
  '${b64(slice(pet1.rom, 0, 1024))}';
export const PET_GRAPHICS_B64 =
  '${b64(slice(pet2.rom, 0, 1024))}';
export const VIC20_UPPER_B64 =
  '${b64(slice(vic.rom, 0, 1024))}';
`;
writeFileSync(join(here, '..', 'src', 'font-roms.mjs'), text);
process.stdout.write('wrote packages/cli/src/font-roms.mjs (three 1024-byte sets)\n');
